### ISSUE TITLE
Running on Linux with Mono

### ISSUE THREAD

**Issue by colinwurtz** [huysentruitw/win-beacon#14]
Might be in over my head here, but has anyone used this library on a linux box with Mono? 

I was able to get the sample project to compile and run on Linux, but it would error out trying to find the device by the PID and VID. I'm assuming the WinUSB driver is what is missing on my Linux machine, any idea if there's a way around that?

**Comment by huysentruitw** [comment]
Never thought anyone would actually try to run this on Linux, because Linux is one of the first platforms that supported iBeacons with the Bluez stack. If there really is a need to run this on Linux, I think we need to add an additional transport which uses RAW BT sockets on Linux instead of WinUSB.

**Comment by colinwurtz** [comment]
I probably have an odd use case...I'm deploying code to a fleet of Raspberry Pis and my main machine is running Windows 7. Was hoping to sync up my development environment with what would be running on each Pi. This would also have the added benefit of developing in Visual Studio.
