### ISSUE TITLE
No Beacon Detected or Advertisements?

### ISSUE THREAD

**Issue by mrlucretius** [huysentruitw/win-beacon#34]
Hello,

This is a great project that will help me greatly for a particular problem. 

I am able to compile and run and point to my CSR dongle, using WinUSB driver. Dongle seems to work fine using stock (not WinUSB) driver for normal windows bluetooth implementation...

However, I cannot see any iBeacons, nor can I see the Advertisement using an Android BLE scanner... I can see my iBeacon device on the Android scanner.

Any ideas? I have a Pluggable dongle on order as well to test. Is there a VS solution that implements the various test functions?

Is it possible some group policy / windows security thing might be interfering?

```C#
static void Main(string[] args)
{            
    using (var hub = new BeaconHub(0x0A12, 0x0001))
    {                
        hub.EnableAdvertising(new Beacon("B9407F30-F5F8-466E-AFF9-25556B57FE6D", 1000, 2000,-52));
        
        hub.BeaconDetected += (sender, e) =>
        {
            Console.WriteLine(e.Beacon.ToString());
        };
        
        Console.ReadKey();
    }
}
```

Thanks!

**Comment by huysentruitw** [comment]
Can you pull the source and include it in your project. Your best bet is to start debugging in the [`LeController`](https://github.com/huysentruitw/win-beacon/blob/master/src/WinBeacon.Stack/Controllers/LeController.cs#L29) class and see which responses you get from the dongle.

If you have a Linux PC at hand or Raspberry PI running linux, you could test the dongle with hcitool and compare data that goes in/out. [This article](https://www.thepolyglotdeveloper.com/2016/09/scan-bluetooth-enabled-ibeacons-via-raspberry-pi-iot-device/) could get you started f.e.

**Comment by mrlucretius** [comment]
I did download the zip file from github... Is that what you mean by pull the source?

I will see if I can get a Linux VM runnning, it seems like that should be a good test?

The beacon is a Tilt Hydrometer:

https://tilthydrometer.com/
https://kvurd.com/blog/tilt-hydrometer-ibeacon-data-format/

**Comment by mrlucretius** [comment]
Hi,

I received a Pluggable USB Radio VID 0A5C, PID 21E8, and this works flawlessly first try after swapping out the (apparently broken) CRC device....

So I guess this is a non-issue, feel free to delete this thread if you like. 

Thanks!

**Comment by huysentruitw** [comment]
Aha, didn't realize you were the same person that sent me an e-mail 🙂 

So, as you already figured out, you can't use the `BeaconHub` class, because that tilt beacon seems to send a different event type:

`00: Event type connectable and scannable undirected advertising`

instead of `04 Scan RSP` (which is checked in the `Beacon.Parse` method at [this line](https://github.com/huysentruitw/win-beacon/blob/master/src/WinBeacon/Beacon.cs#L119)).

Anyway, glad you have it working with the Pluggable USB Radio.

I'm not sure if the CSR dongle will be broken, some chipsets need additional initialization commands in order to get them working. Normally, if the CSR dongle would work with hcitool + BlueZ on Linux, you could figure out the missing command(s).
